package com.example.demo.models.hibernate;

// default package
// Generated Mar. 9, 2022, 1:40:14 p.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients implements java.io.Serializable {

	private String courriel;
	private Utilisateurs utilisateurs;
	private Forfaits forfaits;
	private String typecartedecredit;
	private BigDecimal numero;
	private Date dateexpiration;
	private Set locationses = new HashSet(0);

	public Clients() {
	}

	public Clients(Utilisateurs utilisateurs, Forfaits forfaits, String typecartedecredit, BigDecimal numero, Date dateexpiration) {
        this.utilisateurs = utilisateurs;
        this.forfaits = forfaits;
        this.typecartedecredit = typecartedecredit;
        this.numero = numero;
        this.dateexpiration = dateexpiration;
    }

	public Clients(Utilisateurs utilisateurs, Forfaits forfaits, String typecartedecredit, BigDecimal numero, Date dateexpiration, Set locationses) {
       this.utilisateurs = utilisateurs;
       this.forfaits = forfaits;
       this.typecartedecredit = typecartedecredit;
       this.numero = numero;
       this.dateexpiration = dateexpiration;
       this.locationses = locationses;
    }

	public String getCourriel() {
		return this.courriel;
	}

	public void setCourriel(String courriel) {
		this.courriel = courriel;
	}

	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	public Forfaits getForfaits() {
		return this.forfaits;
	}

	public void setForfaits(Forfaits forfaits) {
		this.forfaits = forfaits;
	}

	public String getTypecartedecredit() {
        return this.typecartedecredit;
    }

	public void setTypecartedecredit(String typecartedecredit) {
        this.typecartedecredit = typecartedecredit;
    }

	public BigDecimal getNumero() {
        return this.numero;
    }

	public void setNumero(BigDecimal numero) {
        this.numero = numero;
    }

	public Date getDateexpiration() {
		return this.dateexpiration;
	}

	public void setDateexpiration(Date dateexpiration) {
		this.dateexpiration = dateexpiration;
	}

	public Set getLocationses() {
		return this.locationses;
	}

	public void setLocationses(Set locationses) {
		this.locationses = locationses;
	}

}
