package com.example.demo.models.hibernate;

// default package
// Generated Mar. 9, 2022, 1:40:14 p.m. by Hibernate Tools 4.3.5.Final

/**
 * Copiefilmsdispo generated by hbm2java
 */
public class Copiefilmsdispo implements java.io.Serializable {

	private CopiefilmsdispoId id;

	public Copiefilmsdispo() {
	}

	public Copiefilmsdispo(CopiefilmsdispoId id) {
		this.id = id;
	}

	public CopiefilmsdispoId getId() {
		return this.id;
	}

	public void setId(CopiefilmsdispoId id) {
		this.id = id;
	}

}
