package com.example.demo.models.hibernate;

// default package
// Generated Mar. 9, 2022, 1:40:14 p.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * CopiefilmsdispoId generated by hbm2java
 */
public class CopiefilmsdispoId implements java.io.Serializable {

	private BigDecimal nocopie;
	private BigDecimal disponible;

	public CopiefilmsdispoId() {
	}

	public CopiefilmsdispoId(BigDecimal nocopie) {
		this.nocopie = nocopie;
	}

	public CopiefilmsdispoId(BigDecimal nocopie, BigDecimal disponible) {
		this.nocopie = nocopie;
		this.disponible = disponible;
	}

	public BigDecimal getNocopie() {
		return this.nocopie;
	}

	public void setNocopie(BigDecimal nocopie) {
		this.nocopie = nocopie;
	}

	public BigDecimal getDisponible() {
		return this.disponible;
	}

	public void setDisponible(BigDecimal disponible) {
		this.disponible = disponible;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CopiefilmsdispoId))
			return false;
		CopiefilmsdispoId castOther = (CopiefilmsdispoId) other;

		return ((this.getNocopie() == castOther.getNocopie()) || (this.getNocopie() != null
				&& castOther.getNocopie() != null && this.getNocopie().equals(castOther.getNocopie())))
				&& ((this.getDisponible() == castOther.getDisponible())
						|| (this.getDisponible() != null && castOther.getDisponible() != null
								&& this.getDisponible().equals(castOther.getDisponible())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNocopie() == null ? 0 : this.getNocopie().hashCode());
		result = 37 * result + (getDisponible() == null ? 0 : this.getDisponible().hashCode());
		return result;
	}

}
