package com.example.demo.models.hibernate;

// default package
// Generated Mar. 9, 2022, 1:40:14 p.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Copiefilms generated by hbm2java
 */
public class Copiefilms implements java.io.Serializable {

	private BigDecimal nocopie;
	private Films films;
	private Set locationses = new HashSet(0);

	public Copiefilms() {
	}

	public Copiefilms(BigDecimal nocopie, Films films) {
		this.nocopie = nocopie;
		this.films = films;
	}

	public Copiefilms(BigDecimal nocopie, Films films, Set locationses) {
		this.nocopie = nocopie;
		this.films = films;
		this.locationses = locationses;
	}

	public BigDecimal getNocopie() {
		return this.nocopie;
	}

	public void setNocopie(BigDecimal nocopie) {
		this.nocopie = nocopie;
	}

	public Films getFilms() {
		return this.films;
	}

	public void setFilms(Films films) {
		this.films = films;
	}

	public Set getLocationses() {
		return this.locationses;
	}

	public void setLocationses(Set locationses) {
		this.locationses = locationses;
	}

}
