package com.example.demo.models.hibernate;

// default package
// Generated Mar. 9, 2022, 1:40:14 p.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * RoleacteursId generated by hbm2java
 */
public class RoleacteursId implements java.io.Serializable {

	private String personnage;
	private BigDecimal filmid;
	private BigDecimal personneid;

	public RoleacteursId() {
	}

	public RoleacteursId(String personnage, BigDecimal filmid, BigDecimal personneid) {
		this.personnage = personnage;
		this.filmid = filmid;
		this.personneid = personneid;
	}

	public String getPersonnage() {
		return this.personnage;
	}

	public void setPersonnage(String personnage) {
		this.personnage = personnage;
	}

	public BigDecimal getFilmid() {
		return this.filmid;
	}

	public void setFilmid(BigDecimal filmid) {
		this.filmid = filmid;
	}

	public BigDecimal getPersonneid() {
		return this.personneid;
	}

	public void setPersonneid(BigDecimal personneid) {
		this.personneid = personneid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleacteursId))
			return false;
		RoleacteursId castOther = (RoleacteursId) other;

		return ((this.getPersonnage() == castOther.getPersonnage()) || (this.getPersonnage() != null
				&& castOther.getPersonnage() != null && this.getPersonnage().equals(castOther.getPersonnage())))
				&& ((this.getFilmid() == castOther.getFilmid()) || (this.getFilmid() != null
						&& castOther.getFilmid() != null && this.getFilmid().equals(castOther.getFilmid())))
				&& ((this.getPersonneid() == castOther.getPersonneid())
						|| (this.getPersonneid() != null && castOther.getPersonneid() != null
								&& this.getPersonneid().equals(castOther.getPersonneid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPersonnage() == null ? 0 : this.getPersonnage().hashCode());
		result = 37 * result + (getFilmid() == null ? 0 : this.getFilmid().hashCode());
		result = 37 * result + (getPersonneid() == null ? 0 : this.getPersonneid().hashCode());
		return result;
	}

}
