package hibernateTest;

// default package
// Generated Mar. 10, 2022, 10:23:51 a.m. by Hibernate Tools 4.3.5.Final

/**
 * Copiefilmsdispo generated by hbm2java
 */
public class Copiefilmsdispo implements java.io.Serializable {

	private CopiefilmsdispoId id;

	public Copiefilmsdispo() {
	}

	public Copiefilmsdispo(CopiefilmsdispoId id) {
		this.id = id;
	}

	public CopiefilmsdispoId getId() {
		return this.id;
	}

	public void setId(CopiefilmsdispoId id) {
		this.id = id;
	}

}
