package hibernateTest;

// default package
// Generated Mar. 10, 2022, 10:23:51 a.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Forfaits generated by hbm2java
 */
public class Forfaits implements java.io.Serializable {

	private char code;
	private String forfait;
	private BigDecimal cout;
	private BigDecimal locationmax;
	private BigDecimal dureemax;
	private Set clientses = new HashSet(0);

	public Forfaits() {
	}

	public Forfaits(char code, String forfait, BigDecimal cout, BigDecimal locationmax) {
		this.code = code;
		this.forfait = forfait;
		this.cout = cout;
		this.locationmax = locationmax;
	}

	public Forfaits(char code, String forfait, BigDecimal cout, BigDecimal locationmax, BigDecimal dureemax,
			Set clientses) {
		this.code = code;
		this.forfait = forfait;
		this.cout = cout;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
		this.clientses = clientses;
	}

	public char getCode() {
		return this.code;
	}

	public void setCode(char code) {
		this.code = code;
	}

	public String getForfait() {
		return this.forfait;
	}

	public void setForfait(String forfait) {
		this.forfait = forfait;
	}

	public BigDecimal getCout() {
		return this.cout;
	}

	public void setCout(BigDecimal cout) {
		this.cout = cout;
	}

	public BigDecimal getLocationmax() {
		return this.locationmax;
	}

	public void setLocationmax(BigDecimal locationmax) {
		this.locationmax = locationmax;
	}

	public BigDecimal getDureemax() {
		return this.dureemax;
	}

	public void setDureemax(BigDecimal dureemax) {
		this.dureemax = dureemax;
	}

	public Set getClientses() {
		return this.clientses;
	}

	public void setClientses(Set clientses) {
		this.clientses = clientses;
	}

}
