package hibernateTest;

// default package
// Generated Mar. 10, 2022, 10:23:51 a.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * LocationsId generated by hbm2java
 */
public class LocationsId implements java.io.Serializable {

	private String clientcourriel;
	private BigDecimal nocopie;

	public LocationsId() {
	}

	public LocationsId(String clientcourriel, BigDecimal nocopie) {
		this.clientcourriel = clientcourriel;
		this.nocopie = nocopie;
	}

	public String getClientcourriel() {
		return this.clientcourriel;
	}

	public void setClientcourriel(String clientcourriel) {
		this.clientcourriel = clientcourriel;
	}

	public BigDecimal getNocopie() {
		return this.nocopie;
	}

	public void setNocopie(BigDecimal nocopie) {
		this.nocopie = nocopie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocationsId))
			return false;
		LocationsId castOther = (LocationsId) other;

		return ((this.getClientcourriel() == castOther.getClientcourriel())
				|| (this.getClientcourriel() != null && castOther.getClientcourriel() != null
						&& this.getClientcourriel().equals(castOther.getClientcourriel())))
				&& ((this.getNocopie() == castOther.getNocopie()) || (this.getNocopie() != null
						&& castOther.getNocopie() != null && this.getNocopie().equals(castOther.getNocopie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getClientcourriel() == null ? 0 : this.getClientcourriel().hashCode());
		result = 37 * result + (getNocopie() == null ? 0 : this.getNocopie().hashCode());
		return result;
	}

}
