package hibernateTest;

// default package
// Generated Mar. 10, 2022, 10:23:51 a.m. by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Paysdeproduction generated by hbm2java
 */
public class Paysdeproduction implements java.io.Serializable {

	private String pays;
	private Set filmses = new HashSet(0);

	public Paysdeproduction() {
	}

	public Paysdeproduction(String pays) {
		this.pays = pays;
	}

	public Paysdeproduction(String pays, Set filmses) {
		this.pays = pays;
		this.filmses = filmses;
	}

	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public Set getFilmses() {
		return this.filmses;
	}

	public void setFilmses(Set filmses) {
		this.filmses = filmses;
	}

}
