package hibernateTest;

// default package
// Generated Mar. 10, 2022, 10:23:51 a.m. by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Scenaristes generated by hbm2java
 */
public class Scenaristes implements java.io.Serializable {

	private String scenariste;
	private Set filmses = new HashSet(0);

	public Scenaristes() {
	}

	public Scenaristes(String scenariste) {
		this.scenariste = scenariste;
	}

	public Scenaristes(String scenariste, Set filmses) {
		this.scenariste = scenariste;
		this.filmses = filmses;
	}

	public String getScenariste() {
		return this.scenariste;
	}

	public void setScenariste(String scenariste) {
		this.scenariste = scenariste;
	}

	public Set getFilmses() {
		return this.filmses;
	}

	public void setFilmses(Set filmses) {
		this.filmses = filmses;
	}

}
