package hibernateTest;

// default package
// Generated Mar. 10, 2022, 10:23:51 a.m. by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Utilisateurs generated by hbm2java
 */
public class Utilisateurs implements java.io.Serializable {

	private String courriel;
	private String nom;
	private String prenom;
	private String notelephone;
	private Date datenaissance;
	private String motdepasse;
	private String adresse;
	private String ville;
	private String province;
	private String codepostal;
	private Employes employes;
	private Clients clients;

	public Utilisateurs() {
	}

	public Utilisateurs(String courriel, String nom, String prenom, String notelephone, Date datenaissance,
			String motdepasse, String adresse, String ville, String province, String codepostal) {
		this.courriel = courriel;
		this.nom = nom;
		this.prenom = prenom;
		this.notelephone = notelephone;
		this.datenaissance = datenaissance;
		this.motdepasse = motdepasse;
		this.adresse = adresse;
		this.ville = ville;
		this.province = province;
		this.codepostal = codepostal;
	}

	public Utilisateurs(String courriel, String nom, String prenom, String notelephone, Date datenaissance,
			String motdepasse, String adresse, String ville, String province, String codepostal, Employes employes,
			Clients clients) {
		this.courriel = courriel;
		this.nom = nom;
		this.prenom = prenom;
		this.notelephone = notelephone;
		this.datenaissance = datenaissance;
		this.motdepasse = motdepasse;
		this.adresse = adresse;
		this.ville = ville;
		this.province = province;
		this.codepostal = codepostal;
		this.employes = employes;
		this.clients = clients;
	}

	public String getCourriel() {
		return this.courriel;
	}

	public void setCourriel(String courriel) {
		this.courriel = courriel;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNotelephone() {
		return this.notelephone;
	}

	public void setNotelephone(String notelephone) {
		this.notelephone = notelephone;
	}

	public Date getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(Date datenaissance) {
		this.datenaissance = datenaissance;
	}

	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCodepostal() {
		return this.codepostal;
	}

	public void setCodepostal(String codepostal) {
		this.codepostal = codepostal;
	}

	public Employes getEmployes() {
		return this.employes;
	}

	public void setEmployes(Employes employes) {
		this.employes = employes;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

}
