// default package
// Generated Mar. 9, 2022, 7:47:02 p.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * BandeannoncesId generated by hbm2java
 */
public class BandeannoncesId implements java.io.Serializable {

	private String url;
	private BigDecimal filmid;

	public BandeannoncesId() {
	}

	public BandeannoncesId(String url, BigDecimal filmid) {
		this.url = url;
		this.filmid = filmid;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public BigDecimal getFilmid() {
		return this.filmid;
	}

	public void setFilmid(BigDecimal filmid) {
		this.filmid = filmid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BandeannoncesId))
			return false;
		BandeannoncesId castOther = (BandeannoncesId) other;

		return ((this.getUrl() == castOther.getUrl())
				|| (this.getUrl() != null && castOther.getUrl() != null && this.getUrl().equals(castOther.getUrl())))
				&& ((this.getFilmid() == castOther.getFilmid()) || (this.getFilmid() != null
						&& castOther.getFilmid() != null && this.getFilmid().equals(castOther.getFilmid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result + (getFilmid() == null ? 0 : this.getFilmid().hashCode());
		return result;
	}

}
