// default package
// Generated Mar. 9, 2022, 7:47:02 p.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients implements java.io.Serializable {

	private String courriel;
	private Utilisateurs utilisateurs;
	private Forfaits forfaits;
	private String typecartedecr�dit;
	private BigDecimal num�ro;
	private Date dateexpiration;
	private Set locationses = new HashSet(0);

	public Clients() {
	}

	public Clients(Utilisateurs utilisateurs, Forfaits forfaits, String typecartedecr�dit, BigDecimal num�ro, Date dateexpiration) {
        this.utilisateurs = utilisateurs;
        this.forfaits = forfaits;
        this.typecartedecr�dit = typecartedecr�dit;
        this.num�ro = num�ro;
        this.dateexpiration = dateexpiration;
    }

	public Clients(Utilisateurs utilisateurs, Forfaits forfaits, String typecartedecr�dit, BigDecimal num�ro, Date dateexpiration, Set locationses) {
       this.utilisateurs = utilisateurs;
       this.forfaits = forfaits;
       this.typecartedecr�dit = typecartedecr�dit;
       this.num�ro = num�ro;
       this.dateexpiration = dateexpiration;
       this.locationses = locationses;
    }

	public String getCourriel() {
		return this.courriel;
	}

	public void setCourriel(String courriel) {
		this.courriel = courriel;
	}

	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	public Forfaits getForfaits() {
		return this.forfaits;
	}

	public void setForfaits(Forfaits forfaits) {
		this.forfaits = forfaits;
	}

	public String getTypecartedecr�dit() {
        return this.typecartedecr�dit;
    }

	public void setTypecartedecr�dit(String typecartedecr�dit) {
        this.typecartedecr�dit = typecartedecr�dit;
    }

	public BigDecimal getNum�ro() {
        return this.num�ro;
    }

	public void setNum�ro(BigDecimal num�ro) {
        this.num�ro = num�ro;
    }

	public Date getDateexpiration() {
		return this.dateexpiration;
	}

	public void setDateexpiration(Date dateexpiration) {
		this.dateexpiration = dateexpiration;
	}

	public Set getLocationses() {
		return this.locationses;
	}

	public void setLocationses(Set locationses) {
		this.locationses = locationses;
	}

}
