// default package
// Generated Mar. 9, 2022, 7:47:02 p.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * Employes generated by hbm2java
 */
public class Employes implements java.io.Serializable {

	private String courriel;
	private Utilisateurs utilisateurs;
	private BigDecimal matricule;

	public Employes() {
	}

	public Employes(Utilisateurs utilisateurs, BigDecimal matricule) {
		this.utilisateurs = utilisateurs;
		this.matricule = matricule;
	}

	public String getCourriel() {
		return this.courriel;
	}

	public void setCourriel(String courriel) {
		this.courriel = courriel;
	}

	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	public BigDecimal getMatricule() {
		return this.matricule;
	}

	public void setMatricule(BigDecimal matricule) {
		this.matricule = matricule;
	}

}
