// default package
// Generated Mar. 9, 2022, 7:47:02 p.m. by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Locations generated by hbm2java
 */
public class Locations implements java.io.Serializable {

	private LocationsId id;
	private Clients clients;
	private Copiefilms copiefilms;
	private Date datedelocation;
	private Date datederetour;

	public Locations() {
	}

	public Locations(LocationsId id, Clients clients, Copiefilms copiefilms, Date datedelocation) {
		this.id = id;
		this.clients = clients;
		this.copiefilms = copiefilms;
		this.datedelocation = datedelocation;
	}

	public Locations(LocationsId id, Clients clients, Copiefilms copiefilms, Date datedelocation, Date datederetour) {
		this.id = id;
		this.clients = clients;
		this.copiefilms = copiefilms;
		this.datedelocation = datedelocation;
		this.datederetour = datederetour;
	}

	public LocationsId getId() {
		return this.id;
	}

	public void setId(LocationsId id) {
		this.id = id;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	public Copiefilms getCopiefilms() {
		return this.copiefilms;
	}

	public void setCopiefilms(Copiefilms copiefilms) {
		this.copiefilms = copiefilms;
	}

	public Date getDatedelocation() {
		return this.datedelocation;
	}

	public void setDatedelocation(Date datedelocation) {
		this.datedelocation = datedelocation;
	}

	public Date getDatederetour() {
		return this.datederetour;
	}

	public void setDatederetour(Date datederetour) {
		this.datederetour = datederetour;
	}

}
