// default package
// Generated Mar. 9, 2022, 7:47:02 p.m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personnes generated by hbm2java
 */
public class Personnes implements java.io.Serializable {

	private BigDecimal personneid;
	private String nom;
	private Date datedenaissance;
	private String lieudenaissance;
	private String photourl;
	private Clob biographie;
	private Set roleacteurses = new HashSet(0);
	private Set filmses = new HashSet(0);

	public Personnes() {
	}

	public Personnes(BigDecimal personneid, String nom) {
		this.personneid = personneid;
		this.nom = nom;
	}

	public Personnes(BigDecimal personneid, String nom, Date datedenaissance, String lieudenaissance, String photourl,
			Clob biographie, Set roleacteurses, Set filmses) {
		this.personneid = personneid;
		this.nom = nom;
		this.datedenaissance = datedenaissance;
		this.lieudenaissance = lieudenaissance;
		this.photourl = photourl;
		this.biographie = biographie;
		this.roleacteurses = roleacteurses;
		this.filmses = filmses;
	}

	public BigDecimal getPersonneid() {
		return this.personneid;
	}

	public void setPersonneid(BigDecimal personneid) {
		this.personneid = personneid;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDatedenaissance() {
		return this.datedenaissance;
	}

	public void setDatedenaissance(Date datedenaissance) {
		this.datedenaissance = datedenaissance;
	}

	public String getLieudenaissance() {
		return this.lieudenaissance;
	}

	public void setLieudenaissance(String lieudenaissance) {
		this.lieudenaissance = lieudenaissance;
	}

	public String getPhotourl() {
		return this.photourl;
	}

	public void setPhotourl(String photourl) {
		this.photourl = photourl;
	}

	public Clob getBiographie() {
		return this.biographie;
	}

	public void setBiographie(Clob biographie) {
		this.biographie = biographie;
	}

	public Set getRoleacteurses() {
		return this.roleacteurses;
	}

	public void setRoleacteurses(Set roleacteurses) {
		this.roleacteurses = roleacteurses;
	}

	public Set getFilmses() {
		return this.filmses;
	}

	public void setFilmses(Set filmses) {
		this.filmses = filmses;
	}

}
