// default package
// Generated Mar. 9, 2022, 7:47:02 p.m. by Hibernate Tools 4.3.5.Final

/**
 * Roleacteurs generated by hbm2java
 */
public class Roleacteurs implements java.io.Serializable {

	private RoleacteursId id;
	private Personnes personnes;
	private Films films;

	public Roleacteurs() {
	}

	public Roleacteurs(RoleacteursId id, Personnes personnes, Films films) {
		this.id = id;
		this.personnes = personnes;
		this.films = films;
	}

	public RoleacteursId getId() {
		return this.id;
	}

	public void setId(RoleacteursId id) {
		this.id = id;
	}

	public Personnes getPersonnes() {
		return this.personnes;
	}

	public void setPersonnes(Personnes personnes) {
		this.personnes = personnes;
	}

	public Films getFilms() {
		return this.films;
	}

	public void setFilms(Films films) {
		this.films = films;
	}

}
