package hibernate;

// default package
// Generated Mar. 9, 2022, 1:40:14 p.m. by Hibernate Tools 4.3.5.Final

/**
 * Bandeannonces generated by hbm2java
 */
public class Bandeannonces implements java.io.Serializable {

	private BandeannoncesId id;
	private Films films;

	public Bandeannonces() {
	}

	public Bandeannonces(BandeannoncesId id, Films films) {
		this.id = id;
		this.films = films;
	}

	public BandeannoncesId getId() {
		return this.id;
	}

	public void setId(BandeannoncesId id) {
		this.id = id;
	}

	public Films getFilms() {
		return this.films;
	}

	public void setFilms(Films films) {
		this.films = films;
	}

}
